import type { Person, Alert, Camera } from "@/types";

export const mockPeople: Person[] = [
  {
    id: "1",
    name: "Rafael Bezerra",
    document: "123.456.789-00",
    phone: "(13) 99999-0001",
    email: "rafael@v8.com",
    category: "RESIDENT",
    categoryLabel: "Morador",
    status: "ACTIVE",
    statusLabel: "Ativo",
    unitId: "A-101",
    createdAt: "2026-03-20T10:00:00Z",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rafael",
  },
  {
    id: "2",
    name: "Mariana Souza",
    document: "987.654.321-00",
    phone: "(13) 99999-0002",
    email: "mariana@v8.com",
    category: "VISITOR",
    categoryLabel: "Visitante",
    status: "INACTIVE",
    statusLabel: "Inativo",
    unitId: "B-202",
    createdAt: "2026-03-19T11:00:00Z",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mariana",
  },
  {
    id: "3",
    name: "Carlos Oliveira",
    document: "456.789.123-00",
    phone: "(13) 99999-0003",
    email: "carlos@v8.com",
    category: "SERVICE_PROVIDER",
    categoryLabel: "Prestador",
    status: "ACTIVE",
    statusLabel: "Ativo",
    unitId: "C-303",
    createdAt: "2026-03-18T14:00:00Z",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
  },
  {
    id: "4",
    name: "Fernanda Lima",
    document: "159.753.486-00",
    phone: "(13) 99999-0004",
    email: "fernanda@v8.com",
    category: "RENTER",
    categoryLabel: "Alugante",
    status: "BLOCKED",
    statusLabel: "Bloqueado",
    unitId: "D-404",
    createdAt: "2026-03-17T09:30:00Z",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fernanda",
  },
  {
    id: "5",
    name: "João Pedro Santos",
    document: "741.852.963-00",
    phone: "(13) 99999-0005",
    email: "joao@v8.com",
    category: "RESIDENT",
    categoryLabel: "Morador",
    status: "INACTIVE",
    statusLabel: "Inativo",
    unitId: "A-102",
    createdAt: "2026-03-16T16:20:00Z",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Joao",
  },
  {
    id: "6",
    name: "Patrícia Gomes",
    document: "852.741.963-00",
    phone: "(13) 99999-0006",
    email: "patricia@v8.com",
    category: "VISITOR",
    categoryLabel: "Visitante",
    status: "ACTIVE",
    statusLabel: "Ativo",
    unitId: "B-201",
    createdAt: "2026-03-15T08:10:00Z",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia",
  },
  {
    id: "7",
    name: "Lucas Ferreira",
    document: "321.654.987-00",
    phone: "(13) 99999-0007",
    email: "lucas@v8.com",
    category: "SERVICE_PROVIDER",
    categoryLabel: "Prestador",
    status: "ACTIVE",
    statusLabel: "Ativo",
    unitId: "E-505",
    createdAt: "2026-03-14T13:45:00Z",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas",
  },
  {
    id: "8",
    name: "Beatriz Costa",
    document: "654.321.987-00",
    phone: "(13) 99999-0008",
    email: "beatriz@v8.com",
    category: "RESIDENT",
    categoryLabel: "Morador",
    status: "ACTIVE",
    statusLabel: "Ativo",
    unitId: "F-606",
    createdAt: "2026-03-13T10:15:00Z",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Beatriz",
  },
];

export const mockAlerts: Alert[] = [
  {
    id: "1",
    title: "Pessoa não identificada",
    description: "Indivíduo desconhecido detectado na entrada principal",
    type: "UNKNOWN_PERSON",
    status: "UNREAD",
    timestamp: new Date(Date.now() - 3 * 60000).toISOString(),
    cameraId: "cam-001",
    location: "Entrada Principal",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Unknown1",
  },
  {
    id: "2",
    title: "Câmera offline",
    description: "Câmera da garagem subsolo perdeu conexão",
    type: "CAMERA_OFFLINE",
    status: "UNREAD",
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    cameraId: "cam-005",
    location: "Garagem Subsolo",
  },
  {
    id: "3",
    title: "Acesso negado",
    description: "Tentativa de acesso com cartão bloqueado",
    type: "ACCESS_DENIED",
    status: "READ",
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    personId: "4",
    location: "Portaria",
  },
  {
    id: "4",
    title: "Pessoa não identificada",
    description: "Indivíduo detectado na área de serviço",
    type: "UNKNOWN_PERSON",
    status: "READ",
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    cameraId: "cam-003",
    location: "Área de Serviço",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Unknown2",
  },
  {
    id: "5",
    title: "Alerta de pânico",
    description: "Botão de pânico acionado na unidade A-101",
    type: "PANIC",
    status: "READ",
    timestamp: new Date(Date.now() - 5 * 3600000).toISOString(),
    personId: "1",
    location: "Unidade A-101",
  },
];

export const mockCameras: Camera[] = [
  {
    id: "cam-001",
    name: "Entrada Principal",
    location: "Portaria",
    status: "ONLINE",
    lastSeen: new Date(Date.now() - 30000).toISOString(),
    snapshotUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=cam001",
  },
  {
    id: "cam-002",
    name: "Garagem Nível 1",
    location: "Garagem",
    status: "ONLINE",
    lastSeen: new Date(Date.now() - 15000).toISOString(),
    snapshotUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=cam002",
  },
  {
    id: "cam-003",
    name: "Área de Serviço",
    location: "Fundos",
    status: "ONLINE",
    lastSeen: new Date(Date.now() - 45000).toISOString(),
    snapshotUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=cam003",
  },
  {
    id: "cam-004",
    name: "Piscina",
    location: "Área de Lazer",
    status: "ONLINE",
    lastSeen: new Date(Date.now() - 20000).toISOString(),
    snapshotUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=cam004",
  },
  {
    id: "cam-005",
    name: "Garagem Subsolo",
    location: "Subsolo",
    status: "OFFLINE",
    lastSeen: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: "cam-006",
    name: "Corredor Bloco A",
    location: "Bloco A",
    status: "ONLINE",
    lastSeen: new Date(Date.now() - 10000).toISOString(),
    snapshotUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=cam006",
  },
];

export const mockDashboardStats = {
  totalPeople: 128,
  activePeople: 98,
  blockedPeople: 4,
  expiredPeople: 26,
  totalAlerts: 156,
  unresolvedAlerts: 12,
  camerasOnline: 18,
  camerasOffline: 2,
  alertsTodayCount: 12,
  unknownPersonsCount: 3,
};

export const mockAlertsTrend = [
  { date: "20/03", count: 8 },
  { date: "21/03", count: 12 },
  { date: "22/03", count: 5 },
  { date: "23/03", count: 15 },
  { date: "24/03", count: 9 },
  { date: "25/03", count: 18 },
  { date: "26/03", count: 12 },
];

export const mockPeopleByCategory = [
  { name: "Moradores", value: 64, fill: "#34c759" },
  { name: "Visitantes", value: 32, fill: "#0a84ff" },
  { name: "Prestadores", value: 20, fill: "#ff9500" },
  { name: "Alugantes", value: 12, fill: "#af52de" },
];
